### ISSUE TITLE
Export always removes pipe, dash and equal sign

### ISSUE THREAD

**Issue by KaiStapel** [Flagbit/Magento-FACTFinder#102]
The following logic seems to remove pipe, dash and equals sign from all attributes during export, while it should only be performed on attributes that are exported to either filterable_attributes or numerical_attributes (see https://github.com/Flagbit/Magento-FACTFinder/wiki/Data-Export#which-values-are-exported).

https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/FACTFinder/Core/Model/Export/Product.php#L980

**Comment by omikron-net** [comment]
This one should be fixed asap, otherwise multi-select attribute values cannot be exported correctly in additional fields.

**Comment by alexander-kotlear** [comment]
The problem lies in the function getAttributeValue. As the solution for MultiSelect attributes would be possible at the Line https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/FACTFinder/Core/Model/Export/Product.php#L690
if ($attribute->getFrontend()->getInputType() !== 'multiselect') {
            $value = $this->_removeTags($value, $storeId);
        }
and after the Line https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/FACTFinder/Core/Model/Export/Product.php#L674
foreach ($value as $key => $attributeValue) {
                    $value[$key] = $this->_removeTags($attributeValue, $storeId);
                }

**Comment by tuegeb** [comment]
In the case of this attribute values array, only the values separator (pipe) should be removed from the single attribute values. The other reserved characters (dash and equals sign) should only be removed additionally from the attribute name/value within the multi-attribute source fields (filterable_attributes and numerical attributes).

**Comment by xpoback** [comment]
I tested it with multiselect attributes (also containing |,#,=) and it looked now fine.

**Comment by xpoback** [comment]
So far it lokks good, as no more complaints :)
