### ISSUE TITLE
Product feed should optionally include new/out-of-stock products

### ISSUE THREAD

**Issue by tuegeb** [Flagbit/Magento-FACTFinder#167]
- Expected behavior: 
product is new/out-of-stock > product.csv already/still contains product, enrichment on FACT-Finder side based on the flag from the stock.csv, the product can be identified on FACT-Finder side for exact-search only mode
- Actual behavior: new/out-of-stock products are missing in product.csv, current stock.csv doesn't help as the products are missing in the FACT-Finder index

**Comment by tuegeb** [comment]
@xpoback: Any news regarding this issue? I am looking forward to your answer.

**Comment by xpoback** [comment]
@tuegeb With the out of stock products it's clear, but what is about the new ones? I mean, waht indicates that the product is new?

**Comment by tuegeb** [comment]
If the creation date-time is within the current day, it's a new product. With the new option, these products should be part of the export.

**Comment by xpoback** [comment]
@tuegeb In case of new products they should appear in the export after magento stock reindex. Or is there any other issue?

**Comment by tuegeb** [comment]
@xpoback: That is not the case for new products, which are currently not on stock. They are missing in the product.csv. If they are on stock in the afternoon and consequently in the stock.csv, still it doesn't help, as FACT-Finder cannot derive basic information from an incomplete products.csv. 
If this use case requires always the product.csv feed to be updated first, it would make the delta-update feature via stock.csv more or less obsolete.

From my perspective it would be great, if you could optionally enforce the export of the new products (their definition can be found above). Alternatively all products should be part of the product.csv. 
Then FACT-Finder can easily determine during the data import based on the current stock.csv whether a product should be found or not.

**Comment by tuegeb** [comment]
@xpoback: Any news regarding this issue?

**Comment by xpoback** [comment]
@tuegeb 
Let's check again if I understood  that definition properly.
Assume, in the morning, let's say at 6 a.m. all products get transferred from the shop to FF. At 11 a.m the owner decides to add a couple of new products. Since the next FF export is only 15 hours later, the newly added product are missing the whole day and we want to avoid this. Is this correct?

If so, how should we check whether any new products have appeared? In case the product was added through admin panel, I can add an observer, but if this is done but some import script, which writes data directly to the db, we should probably check it every let's say 2 hours.
When a new product was detected, we add it to the end of the export file and trigger FF import or should  it be some new sort of export files with only delta product data?

**Comment by tuegeb** [comment]
@xpoback: Thanks for the already implemented solution for the export of sold out products. I think that should be sufficient for the moment. If further adjustments are needed, we will come back to you.
