### ISSUE TITLE
Checkout tracking product ID but not parent ID

### ISSUE THREAD

**Issue by hollymurdoch** [Flagbit/Magento-FACTFinder#188]
- Release 4.10
- Magento version 1.9.2.4

https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/FACTFinder/Tracking/sql/factfinder_tracking_setup/upgrade-4.1.2-4.1.11.php

The above was added on 26th Sept to resolve an issue with IDs reported in checkout events. This has been working well, however it has now become apparent that checkout events are only reporting the product ID, whereas click and cart events are reporting the parent ID. Please can parent ID be provided in the checkout event tracking so that FF can correctly attribute sales.

**Comment by xpoback** [comment]
Until now it was only reporting parent IDs and in case if the product identifier was SKU, most of the configurable SKUs were wrong, since SKU in magento _order items_ don't normally correspond to real ones.
This fix should help with that. The only possible issue is the price, since configurable children have no price and therefore 0.00 is transferred in this case, while for the parent it functions well.

**Comment by xpoback** [comment]
Now it works correctly with bundle and configurable products.

**Comment by tuegeb** [comment]
@xpoback: The tracking request will be rejected with an 400 response code due to an empty parameter "masterId" when you track a simple product without parent product. 
Please ensure that `$item->getProduct()->getData($idFieldName)` is used as a fallback value in `$parentProductId` (https://github.com/Flagbit/Magento-FACTFinder/blob/1f1f7376bddc34561d4b1f5079aea7b5c482944d/src/app/code/community/FACTFinder/Tracking/Model/Observer.php#L194 may be null). Thanks!

**Comment by xpoback** [comment]
@tuegeb Thanks for reporting. Solved.
