### ISSUE TITLE
Not JS merge compliant

### ISSUE THREAD

**Issue by dicotout** [Flagbit/Magento-FACTFinder#217]
https://github.com/Flagbit/Magento-FACTFinder/blob/73061d7e6dbb1935b9e288bda513b125c042dd87/src/js/factfinder/suggest.js#L183

Hello,

This part of code : 
`function($super, form, field, emptyText, i18n, defaultChannel) {
        $super(form, field, emptyText);`
provocke a JS crash after our automatic JS merging. It is compressed as : 
`function(t, f, e, x, i, d) { t(f, e, x);`
Which throw the error :

> t is not a function

How this code can be modified to be mergeable compliant ?

Thanks

**Comment by mbraeuner** [comment]
Which minify/compressor tool do you use and which tool merges the scripts? Maybe the scripts are merged in wrong order. 
If the plain javascript is running fine the problem is the compressor in most cases or the order while merging. The magento standard merge functionality will merge correctly if you do not touch the creation process.

The problem is not in this line of code. The problem is caused before the call of this function, because the parameter "t" does not contain a callable. "t" is coming from outside this function. 
If you want to find the root cause, you should have a look in your js debuggers stack trace to see where the given parameters come from and why they are broken.

**Comment by dicotout** [comment]
Yes you are right. I excluded this file from my merging tool and now all is ok.
Thanks
