### ISSUE TITLE
session-id and sourceRefKey must exist with every request

### ISSUE THREAD

**Issue by rudibatt** [Flagbit/Magento-FACTFinder#60]
- always use the last known refKey as sourceRefKey
- with every request also send the session id

**Comment by tuegeb** [comment]
Since version 4 (RC already available: https://github.com/Flagbit/Magento-FACTFinder/releases/tag/v4.0.0-rc.1, latest revision in branch https://github.com/Flagbit/Magento-FACTFinder/tree/next) the session id is added if the personalization module is enabled. With the new tracking 1.1 API the reference key isn't needed anymore.
