### ISSUE TITLE
to many exception logs for one failed request

### ISSUE THREAD

**Issue by rudibatt** [Flagbit/Magento-FACTFinder#67]
There is a "Mage::logException($e);" in "Flagbit_FactFinder_Model_Facade->_getFactFinderObject"
that will cause a lot of logged Exception (around 10) for every single failed search request.
This should be optimized so failed requests are just logged once and even that can be disabled.

**Comment by xpoback** [comment]
That line logs the exceptions, that come from the library and cannot be removed. The amount of exception logs equals the amount of erroneus requests to the lib. This cannot be reduced without essential error data loss or\and without modifying the library itself.

**Comment by rudibatt** [comment]
What kind of library modification could help here? Should there be a validator that could be used before requesting the library?

**Comment by xpoback** [comment]
[Deeper look and some modifications](https://github.com/Flagbit/Magento-FACTFinder/commit/e1cbfd5c8cd901fcadfc68880ed2f6a0ab2310d8) into the module allowed to avoid most of the not needed exception logs.

What would be good to have - some general status check. [The old one](https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/FACTFinder/Core/Model/Facade.php#L671) through the status helper does not work, because the corresponding method was removed from the newer lib and there's no way to get the current app status without using different reflection tricks. Though, it's not essential.

**Comment by rudibatt** [comment]
Cool! Thanks. Looks promising. 
By the way, there is still a [status object from the search request](https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/lib/FACTFinder/Adapter/Search.php#L230). What else would be expected for a "general app status"?

**Comment by xpoback** [comment]
This function is for search and I made use of it in the last commit (so if it failed, we dont request after search navigation, paging and sorting). It checks if search reasults are accessible.
What I meant is general check, if fact finder is available at all, so if it's sudenly not, we omit making any requests. Or something like that. But as I already mentioned, it's not essentional.
