### ISSUE TITLE
Auto Suggest not Working on Android/Chrome devices

### ISSUE THREAD

**Issue by matthias-ebner** [Flagbit/Magento-FACTFinder#83]
The auto suggest feature doesn't work on android devices using chrome. Tested this with the latest chrome for android browser on a Samsung Tablet as well as on a nexus 4 mobile phone.
A quick remote debugging didn't show any errors in the console, so it's apparently not some obvious issue. Didn't check further though.

**Comment by tkn98** [comment]
@matthias-ebner: It makes not much sense to just report that something doesn't work while not saying what the expected behavior was and how it differed from that.

As you're reporting from your point of view, this is necessary for a good issue report and also for other users - like me - to find out if they have the same issue or not.

**Comment by tkn98** [comment]
@matthias-ebner: Maybe if you still remember what the case was, please update the ticket.

**Comment by xpoback** [comment]
@matthias-ebner in case the issue is not updated until the 14th od December, it will be closed
